import type { JobApplication } from "./types";

const now = new Date().toISOString();

export const SAMPLE_APPLICATIONS: JobApplication[] = [
  {
    id: "sample-1",
    company: "Northstar Labs",
    role: "Frontend Engineer",
    jobUrl: "https://example.com/jobs/frontend-engineer",
    status: "applied",
    nextAction: "Follow up with recruiter",
    notes: "React-heavy product role with a small platform team.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-2",
    company: "OrbitPay",
    role: "Full Stack Developer",
    status: "interview",
    deadline: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    nextAction: "Prepare system design examples",
    notes: "Next round covers architecture and API design.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-3",
    company: "PixelForge",
    role: "Product Engineer",
    status: "take-home",
    deadline: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    nextAction: "Finish take-home submission",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-4",
    company: "BrightDesk",
    role: "Frontend Platform Engineer",
    status: "screening",
    nextAction: "Send portfolio links",
    notes: "Hiring manager asked for production UI examples.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-5",
    company: "CloudNest",
    role: "React Developer",
    status: "interview",
    deadline: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    nextAction: "Review recent project tradeoffs",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-6",
    company: "LedgerLoop",
    role: "Software Engineer",
    status: "rejected",
    nextAction: "Archive notes and move on",
    notes: "Role moved forward with candidates who had fintech experience.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-7",
    company: "SignalWorks",
    role: "Product Frontend Engineer",
    status: "rejected",
    nextAction: "Save recruiter contact for future openings",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "sample-8",
    company: "AtlasGrid",
    role: "UI Engineer",
    status: "rejected",
    nextAction: "Review feedback before applying again",
    createdAt: now,
    updatedAt: now,
  },
];
